412072: [Table 2] Papyrus must provide tests for the table of views https://bugs.eclipse.org/bugs/show_bug.cgi?id=412072
Try a correction to avoid the exception 
org.eclipse.swt.SWTException: Failed to execute runnable (org.eclipse.swt.SWTException: Widget is disposed)

due to while(Display.getDefault.readAndDisplatch());